### ISSUE TITLE
Error while building Docker Image

### ISSUE THREAD

**Issue by xilenteyex** [SymbioticLab/tensorflow-salus#3]
Hi, I am interested in running Salus with tensorflow. I did the following steps:

I cloned the repo:
``` 
git clone https://github.com/SymbioticLab/tensorflow-salus
```
then i changed directory to docker:
```
cd tensorflow-salus/docker
```
and build a docker image:
```
sudo docker build -t salus .
```
It gives the following error:

> Step 2/6 : COPY tensorflow tensorflow                                                                                     
> COPY failed: stat /var/lib/docker/tmp/docker-builder519378597/tensorflow: no such file or directory 

It will be great if someone can help me resolve this.
Thanks!

**Comment by Aetf** [comment]
The docker image isn't meant to be built directly like this. Please refer to the appendix section of the [paper](https://unlimited-code.works/assets/pub/yu20mlsys/yu20mlsys.pdf) for detailed build instructions.

**Comment by xilenteyex** [comment]
Hi @Aetf ,
Thanks for guiding me to the more descriptive instructions:
As mentioned in the [paper](https://unlimited-code.works/assets/pub/yu20mlsys/yu20mlsys.pdf), 
I first built a container with [image](https://gitlab.com/Salus/builder), then:
1. Installed [bazel 0.5.4](https://github.com/bazelbuild/bazel/releases/tag/0.5.4) inside this container
2. cloned [tensorflow-salus](https://github.com/SymbioticLab/tensorflow-salus) repo
3. cd into tensorflow-salus repo directory
4. executed inv deps && inv init
   i. It runs into error: **unable to find zeromq**
   ii. I tried installing zeromq using spack manually as well: 
       still the same error.

Any help on resolving this will be much appreciated.
Thanks!

**Comment by xilenteyex** [comment]
Hi @Aetf,
I was able to resolve all the dependency issues and compile tensorflow-salus successfully. Next, I want to run one of the existing benchmaarks e.g. [card304](https://github.com/SymbioticLab/Salus/blob/master/benchmarks/exps/card304.py). Looking at the benchmark code, it looks like [**card304** requires the compiled binary for Salus server](https://github.com/SymbioticLab/Salus/blob/b2a194e7e4654b51dbd8d8fc1577fb1e9915ca6f/benchmarks/driver/server/__init__.py#L75). 
I also, notice that there is a docker image available for [Salus Server](https://github.com/SymbioticLab/Salus). I was able to successfully launch the server using the docker image.  Is there a way to use the exisiting salus server running in a separate container instead of compiling in the same container as the tensorflow-salus?

**Comment by Aetf** [comment]
You can use something like docker-compose to link the ports on two containers together.

The benchmark code assumes it can control the salus server directly. But I think it should be possible to change the relevant server driver part to noop to make it use an existing salus server.

**Comment by xilenteyex** [comment]
Hi @Aetf,
I was able to use the following commands to bring both the running dockers on the same network:
```
docker network create mynet
docker network connect mynet salus-server-container
docker network connect mynet tensorflow-salus-container
```
With in the same network, salus-server has ip: 172.18.0.2 and  tensorflow-salus has ip: 172.18.0.3. But, it looks like in the benchmark driver code (inside tensorflow-salus container), salus-server ip and port has been hard-coded to **127.0.0.1:5501** .
Is there an easy way to fix this?

**Comment by Aetf** [comment]
Hmm, maybe you can try clone the code locally, and modify that. Then map the code directory into the container, so the newer version of the code can be used.

**Comment by xilenteyex** [comment]
@Aetf, yeah I already access to the code. I am unsure which parts of the code I need to modify. If you can guide me about how to modify the code, that will be helpful.

Thanks!

**Comment by Aetf** [comment]
Which one are you trying to run? The IP isn't set in the benchmark driver, but is simply a target string in actual workload scripts. There are three kinds of workloads
* Those in unit tests `tests/test_tf`, the target string is set in `tests/test_tf/__init__.py` [L100](https://github.com/SymbioticLab/Salus/blob/master/tests/test_tf/__init__.py#L100) and [L108](https://github.com/SymbioticLab/Salus/blob/master/tests/test_tf/__init__.py#L108)
* tf_cnn_benchmarks: in [`scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py`](https://github.com/Aetf/tf_benchmarks/blob/zrpcsession/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py#L1311) (this is another repo)
* Fathom (https://github.com/Aetf/fathom), these are read from the benchmark driver's salus server endpoint, which can be set on the driver command line: https://github.com/SymbioticLab/Salus/blob/b2a194e7e4654b51dbd8d8fc1577fb1e9915ca6f/benchmarks/driver/server/__init__.py#L44 (I assume you already skipped the server starting code in the driver, so setting this just informs Fathom of the correct address)

**Comment by xilenteyex** [comment]
I am running the following command inside Salus repo:
```
python -m benchmarks.driver card304
```
I think it tries to run tf_cnn_benchmarks: [`scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py`](https://github.com/Aetf/tf_benchmarks/blob/zrpcsession/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py#L1311).
When I run the above command, execution gets stuck and I see the following logger output:
`[2021-01-29 20:56:23,950] [benchmarks.exps] [INFO] Waiting workload to be ready on /tmp/tmpkCRCpC/fifotrain`
I updated [L1311](https://github.com/Aetf/tf_benchmarks/blob/zrpcsession/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py#L1311), still the same error.
Edit: I also updated [L1461](https://github.com/Aetf/tf_benchmarks/blob/zrpcsession/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py#L1461), still same error.
Is this stuck for salus-server or am I missing something here ?
Yes, I already commented the server starting code since I have it running in a separate docker container.

**Comment by Aetf** [comment]
The benchmark driver waits on a pipe for the workload to be ready, the workload should signal it's ready by writing a byte to the pipe (https://github.com/Aetf/tf_benchmarks/blob/zrpcsession/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py#L957).

Check the workload output file for anything wrong.

**Comment by shushengyuan** [comment]
> The docker image isn't meant to be built directly like this. Please refer to the appendix section of the [paper](https://unlimited-code.works/assets/pub/yu20mlsys/yu20mlsys.pdf) for detailed build instructions.

hmm, I didn't find THE APPEDDIX SECTION of the paper, could you tell me where i can find it ?

**Comment by Aetf** [comment]
@shushengyuan The appendix is in the published conference version of the paper. The link on my website was updated. Here's the new one: https://unlimited-code.works/assets/pub/salus:mlsys20/salus-mlsys20.pdf

**Comment by shushengyuan** [comment]
> @shushengyuan The appendix is in the published conference version of the paper. The link on my website was updated. Here's the new one: https://unlimited-code.works/assets/pub/salus:mlsys20/salus-mlsys20.pdf

thank you! it helps a lot

**Comment by shushengyuan** [comment]
> Hi @Aetf ,
> Thanks for guiding me to the more descriptive instructions:
> As mentioned in the [paper](https://unlimited-code.works/assets/pub/yu20mlsys/yu20mlsys.pdf),
> I first built a container with [image](https://gitlab.com/Salus/builder), then:
> 
> 1. Installed [bazel 0.5.4](https://github.com/bazelbuild/bazel/releases/tag/0.5.4) inside this container
> 2. cloned [tensorflow-salus](https://github.com/SymbioticLab/tensorflow-salus) repo
> 3. cd into tensorflow-salus repo directory
> 4. executed inv deps && inv init
>    i. It runs into error: **unable to find zeromq**
>    ii. I tried installing zeromq using spack manually as well:
>    still the same error.
> 
> Any help on resolving this will be much appreciated.
> Thanks!

HI, i met the same question about zeromq,could you tell me how to solve it?
Thanks!

**Comment by Aetf** [comment]
@shushengyuan Hi, zeromq seems to have their release url changed.

`inv deps` just installs some dependencies. There are actually only a few
* `zeromq` v4.2.5
*  `cppzmq` v4.3.0
*  python-numpy

So instead of running `inv deps`, you can download and compile the first two manually and install them to prefix `<repo>/spack-packages`. Also don't forget to install numpy.

After this `inv init` should be run without problem.

**Comment by ShreyasheeSinha** [comment]
Hi @Aetf,
Do we have to separately install cython? If not, I have been trying to build tensorflow-salus using `inv build` and I bump into this. Initially I was on Python 3.5 and that generated some errors early on, hence shifted to 3.6. Also my bazel version is 0.5.4.

```
root@c3c16b3207f1:/salus/tensorflow-salus# python -V
Python 3.6.3
root@c3c16b3207f1:/salus/tensorflow-salus# inv build
bazel build -c opt --config=cuda  //tensorflow:libtensorflow_framework.so //tensorflow:libtensorflow_kernels.so //tensorflow/tools/pip_package:build_pip_package
...................
WARNING: /salus/tensorflow-salus/tensorflow/core/BUILD:1814:1: in includes attribute of cc_library rule //tensorflow/core:framework_headers_lib: '../../external/nsync/public' resolves to 'external/nsync/public' not below the relative path of its package 'tensorflow/core'. This will be an error in the future. Since this rule was created by the macro 'cc_header_only_library', the error might have been caused by the macro implementation in /salus/tensorflow-salus/tensorflow/tensorflow.bzl:1138:30.
WARNING: /salus/tensorflow-salus/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': No longer supported. Switch to SavedModel immediately.
WARNING: /salus/tensorflow-salus/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': No longer supported. Switch to SavedModel immediately.
INFO: Found 3 targets...
ERROR: /salus/tensorflow-salus/tensorflow/python/BUILD:4586:1: Executing genrule //tensorflow/python:framework_fast_tensor_util_cython_translation failed (Exit 1).
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/ef6f2d7aa9e625bf367e9f2cf4a24bad/execroot/org_tensorflow/bazel-out/host/bin/external/cython/cython_binary.runfiles/org_tensorflow/../cython/cython.py", line 17, in <module>
    main(command_line = 1)
  File "/root/.cache/bazel/_bazel_root/ef6f2d7aa9e625bf367e9f2cf4a24bad/external/cython/Cython/Compiler/Main.py", line 720, in main
    result = compile(sources, options)
  File "/root/.cache/bazel/_bazel_root/ef6f2d7aa9e625bf367e9f2cf4a24bad/external/cython/Cython/Compiler/Main.py", line 695, in compile
    return compile_multiple(source, options)
  File "/root/.cache/bazel/_bazel_root/ef6f2d7aa9e625bf367e9f2cf4a24bad/external/cython/Cython/Compiler/Main.py", line 666, in compile_multiple
    context = options.create_context()
  File "/root/.cache/bazel/_bazel_root/ef6f2d7aa9e625bf367e9f2cf4a24bad/external/cython/Cython/Compiler/Main.py", line 589, in create_context
    return Context(self.include_path, self.compiler_directives,
  File "/root/.cache/bazel/_bazel_root/ef6f2d7aa9e625bf367e9f2cf4a24bad/external/cython/Cython/Compiler/Main.py", line 75, in __init__
    from . import Builtin, CythonScope
  File "/root/.cache/bazel/_bazel_root/ef6f2d7aa9e625bf367e9f2cf4a24bad/external/cython/Cython/Compiler/CythonScope.py", line 5, in <module>
    from .UtilityCode import CythonUtilityCode
  File "/root/.cache/bazel/_bazel_root/ef6f2d7aa9e625bf367e9f2cf4a24bad/external/cython/Cython/Compiler/UtilityCode.py", line 3, in <module>
    from .TreeFragment import parse_from_strings, StringParseContext
  File "/root/.cache/bazel/_bazel_root/ef6f2d7aa9e625bf367e9f2cf4a24bad/external/cython/Cython/Compiler/TreeFragment.py", line 17, in <module>
    from .Visitor import VisitorTransform
  File "/root/.cache/bazel/_bazel_root/ef6f2d7aa9e625bf367e9f2cf4a24bad/external/cython/Cython/Compiler/Visitor.py", line 15, in <module>
    from . import ExprNodes
  File "/root/.cache/bazel/_bazel_root/ef6f2d7aa9e625bf367e9f2cf4a24bad/external/cython/Cython/Compiler/ExprNodes.py", line 2875
    await = None
          ^
SyntaxError: invalid syntax
INFO: Elapsed time: 44.710s, Critical Path: 7.53s
```

**Comment by Aetf** [comment]
Python 3.6 is too new for TF 1.5, which is what this repo based on. I'm afraid you have to stay on Python 3.5.

**Comment by ShreyasheeSinha** [comment]
<img width="815" alt="Screen Shot 2021-12-07 at 11 36 34 PM" src="https://user-images.githubusercontent.com/94020634/145148980-9716b58e-a3a0-4905-a664-3f2aa12ba85c.png">


Hi, any idea why I keep bumping on this?

**Comment by ShreyasheeSinha** [comment]
Also, both python and python3 versions are supposed to be 3.5?
