### ISSUE TITLE
Understanding Salus Scheduling component in tensorflow-salus

### ISSUE THREAD

**Issue by xilenteyex** [SymbioticLab/tensorflow-salus#4]
Hi, I am working on a very similar problem, but mostly targeted to inference jobs. I am more interested in the scheduling part of Salus. If you can share the code which does fine grained/coarse grained scheduling inside tensorflow-code, that would be very helpful for me.

Thanks!

**Comment by Aetf** [comment]
Tensorflow does its own scheduling of operators/kernels in the [executor](https://github.com/SymbioticLab/tensorflow-salus/blob/master/tensorflow/core/common_runtime/executor.cc) in common_runtime.

Salus does iteration level scheduling with its [scheduler](https://github.com/SymbioticLab/Salus/tree/master/src/execution/scheduler).
